In [4]:
import tensorflow as tf

myName = tf.Variable("Karan", tf.string)
print(myName)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Karan'>


In [12]:
r1 = tf.Variable([20, 21, 22, 5], tf.int64)
r2 = tf.Variable([["Test", "Pass", "Green"], ["test", "fail", "red"]], tf.string)

In [6]:
tf.rank(r2)
tf.rank(myName)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [13]:
r2.shape 

TensorShape([2, 3])

### Changing Shape
Argument [x,y,z] can be thought of as x lists, of y lists, of z elements.  
Putting -1 as an argument lets the function figure out the appropriate value for that dimension.

In [24]:
t1 = tf.ones([1, 2, 3]) 
print(t1)
t2 = tf.reshape(t1, [2,3,1])
print(t2)
t3 = tf.reshape(t2, [-1,3]) # 6 elements, 2 x 3 = 6, therefore the first argument is 2.
print(t3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
